from collections import OrderedDict

structure = OrderedDict([
    ('Unknown0'     ,'read_int32_LE'),
    ('Unknown1'     ,'read_float_LE'),
    ('Unknown2'     ,'read_int32_LE'),
    ('base_points'  ,'read_int32_LE'),
    ('Unknown4'     ,'read_float_LE'),
    ('Unknown5'     ,'read_float_LE'),
    ('bonus_points' ,'read_int32_LE'),
    ('Unknown7'     ,'read_int32_LE'),
    ('Unknown8_0'   ,'read_int32_LE'),
    ('Unknown8_1'   ,'read_int32_LE'),
    ('Unknown9'     ,'read_float_LE'),
    ('Unknown10'    ,'read_float_LE'),
    ('Unknown11_0'  ,'read_int32_LE'),
    ('Unknown11_1'  ,'read_int32_LE'),
    ('Unknown11_2'  ,'read_int32_LE'),
    ('Unknown11_3'  ,'read_int32_LE'),
    ('Unknown12'    ,'read_int32_LE'),
    ('Unknown13'    ,'read_float_LE'),
    ('spell_id'     ,'read_int32_LE'),
    ('Unknown15'    ,'read_int32_LE'),
    ('Unknown16'    ,'read_float_LE'),
    ('Unknown17'    ,'read_int16_LE'),
    ('Unknown18'    ,'read_int16_LE'),
    ('difficulty_id','read_int8_LE'),
    ('Unknown20'    ,'read_uint8_LE'),
    ('Unknown21'    ,'read_int8_LE'),
    ('Unknown22_0'  ,'read_uint8_LE'),
    ('Unknown22_1'  ,'read_uint8_LE'),
    ('Unknown23_0'  ,'read_uint8_LE'),
    ('Unknown23_1'  ,'read_uint8_LE'),
    ('effect_no'    ,'read_int8_LE'),
])      

